# Created by Yuan Wang (yuanw8)
# Cloud and Cluster Computing Assignment 2
# Semester 1, 2018

---
#- hosts: targetIns
#  tasks:

    - name: install python essential
      apt:
        name: python-setuptools
        force_apt_get: yes
        state: latest

    - name: install git
      apt:
        name: git
        state: latest

#sudo easy_install apache2
    - name: install apache2
      apt:
        name: apache2
        force_apt_get: yes
        state: latest

#sudo easy_install pip
    - name: install pip
      easy_install:
        name: pip
        state: latest

#pip install tweepy
    - name: install packages for python2
      pip:
        name: "{{ item }}"
        state: latest
      with_items:
        - tweepy
        - textblob
        - configparser
        - couchdb

...