# Created by Yuan Wang (yuanw8)
# Cloud and Cluster Computing Assignment 2
# Semester 1, 2018

---

#- hosts: masterIns
#  tasks:

#curl -X POST -H "Content-Type: application/json" http://admin:password@127.0.0.1:5984/_cluster_setup -d '{"action": "enable_cluster", "bind_address":"0.0.0.0", "username": "admin", "password":"password", "port": 15984, "node_count": "3", "remote_node": "<remote-node-ip>", "remote_current_user": "<remote-node-username>", "remote_current_password": "<remote-node-password>" }'
    - name: master enable cluster -> slave1
      uri:
        url: http://{{ ansible_default_ipv4.address }}:5984/_cluster_setup
        method: POST
        force_basic_auth: yes
        body_format: json
        user: admin
        password: team20
        body: '{"action": "enable_cluster", "bind_address":"0.0.0.0", "username": "admin", "password":"team20", "port": 5984, "node_count": "3", "remote_node": "115.146.86.111", "remote_current_user": "admin", "remote_current_password": "team20" }'

#curl -X POST -H "Content-Type: application/json" http://admin:password@127.0.0.1:5984/_cluster_setup -d '{"action": "enable_cluster", "bind_address":"0.0.0.0", "username": "admin", "password":"password", "port": 15984, "node_count": "3", "remote_node": "<remote-node-ip>", "remote_current_user": "<remote-node-username>", "remote_current_password": "<remote-node-password>" }'
    - name: master enable cluster -> slave2
      uri:
        url: http://admin:team20@{{ ansible_default_ipv4.address }}:5984/_cluster_setup
        method: POST
        body_format: json
        user: admin
        password: team20
        body: '{"action": "enable_cluster", "bind_address":"0.0.0.0", "username": "admin", "password":"team20", "port": 5984, "node_count": "3", "remote_node": "115.146.86.90", "remote_current_user": "admin", "remote_current_password": "team20" }'


#curl -X POST -H "Content-Type: application/json" http://admin:password@127.0.0.1:5984/_cluster_setup -d '{"action": "add_node", "host":"<remote-node-ip>", "port": "<remote-node-port>", "username": "admin", "password":"password"}'
    - name: master add node1
      uri:
        url: http://127.0.0.1:5984/_cluster_setup
        method: POST
        force_basic_auth: yes
        user: admin
        password: team20
        body_format: json
        body: '{"action": "add_node", "host":"115.146.86.111", "port": "5984", "username": "admin", "password":"team20"}'

#curl -X POST -H "Content-Type: application/json" http://admin:password@127.0.0.1:5984/_cluster_setup -d '{"action": "add_node", "host":"<remote-node-ip>", "port": "<remote-node-port>", "username": "admin", "password":"password"}'
    - name: master add node2
      uri:
        url: http://{{ ansible_default_ipv4.address }}:5984/_cluster_setup
        method: POST
        force_basic_auth: yes
        body_format: json
        user: admin
        password: team20
        body: '{"action": "add_node", "host":"115.146.86.90", "port": "5984", "username": "admin", "password":"team20"}'


#curl -X POST -H "Content-Type: application/json" http://admin:password@127.0.0.1:5984/_cluster_setup -d '{"action": "finish_cluster"}'
    - name: finish cluster
      uri:
        url: http://{{ ansible_default_ipv4.address }}:5984/_cluster_setup
        method: POST
        force_basic_auth: yes
        body_format: json
        user: admin
        password: team20
        body: '{"action": "finish_cluster"}'



...
