# Created by Yuan Wang (yuanw8)
# Cloud and Cluster Computing Assignment 2
# Semester 1, 2018

---

#- hosts: targetIns
#  tasks:

#curl -X POST -H "Content-Type: application/json" http://admin:password@127.0.0.1:5984/_cluster_setup -d '{"action": "enable_cluster", "bind_address":"0.0.0.0", "username": "admin", "password":"password", "node_count":"3"}'
    - name: enable cluster
      uri:
        url: http://{{ ansible_default_ipv4.address }}:5984/_cluster_setup
        method: POST
        force_basic_auth: yes
        body_format: json
        user: admin
        password: team20
        body: '{"action": "enable_cluster", "bind_address":"0.0.0.0", "username": "admin", "password":"team20", "node_count":"3"}'

...